remote_theme : volny/creative-theme-jekyll

# Site settings
title: kiyoung blog
email: ky.jang@purple.io
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kiyoung.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
